apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-restapi
  labels:
    app: simple-restapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-restapi
  template:
    metadata:
      labels:
        app: simple-restapi
    spec:
      containers:
      - name: simple-restapi
        image: varunraj7/simple-restapi:v1
        ports:
        - containerPort: 8080